# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'WhereAreU' do
  # Pods for WhereAreU
  pod 'GoogleMaps', '5.1.0.0'
  pod 'Socket.IO-Client-Swift', '~> 16.0.1'

end
